site_name: ERPNext China OPC
site_description: 专为中国“一人公司”和独立开发者打造的开源合规套件
repo_url: https://github.com/kingpy-tech/erpnext_china_opc
edit_uri: edit/main/docs/

theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight

nav:
  - 首页: index.md
  - 安装部署: 01_ERPNext_Micro_Server_Install.md
  - 财务初始化:
    - 科目表导入: 02_Chart_of_Accounts_Import.md
    - 命名规则配置: 03_Document_Naming_Series.md
  - 本地化:
    - 自定义翻译: 04_Custom_Translation_Import.md
